spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
    application: 
      name: microservicecloud-config-rhy-dev
      
---
spring:
  profiles: test
    application: 
      name: microservicecloud-config-rhy-test
      
#UTF-8
     